### ISSUE TITLE
Problem beim mehrsprachigen Abspeichern von Attributen

### ISSUE THREAD

**Issue by flash7x** [leofonic/jxAttrEdit#1]
**Beschreibung 1**
1. ich schreibe einen beliebigen Wert in die deutsche Version und speichere ab.
2. wechsele die Sprache zu englisch (oder auch andere Sprachen)
3. lasse die englische Version des Attributs leer und speichere ab
4. wechsle zu deutsch und sehe, dass die deutsche Version nun auch leer ist.

**Beschreibung 2**
Im extremfall, hat man auf deutsch 30 Attribute gepflegt und gespeichert, wechselt auf englisch, pflegt dort nur 3 Attrbute, klickt auf speichern und löscht somit 27 auf der deutschen Seite, da diese in englisch keinen Wert hatten.

Mam muss quasi aufpassen, dass man erst auf speichern klickt, wenn die Werte in allen relevanten Sprachen parallel gepflegt wurden.

**Die Frage die nun in den Raum tritt: warum in Sprache-X 20 Attribute und in Sprache-Y nur 5 Attribute zu pflegen**

Das ist richtig. Wenn man dieses Verhalten jedoch nicht kenn und im Nachgang für sämtlche Produkte und Attribute eine zweite Sprache nachpflegt **ohne** wieder in die erste Sprache zurück zu schalten - da man ja das obige Verhalten nicht erwartet - dann stellt man unter Umständen erst spät fest, dass man sehr viele Attribute der Originalsprache (in dem Fall deutsch) gelöscht hat.

Oxid Version: Enterprise 6.1.5

**Comment by leofonic** [comment]
Hallo ich habe das automatische Löschen bei Attributen ohne Wert entfernt, außerdem auch die Sprachauswahl, die hat den bottom-Frame vom Top-Frame entkoppelt. Also jetzt bleiben die Attribute dem Artikel zugeordnet auch wenn sie keinen Wert mehr haben, denn es könnte ja noch einen Wert in einer anderen Sprache geben. Bitte mal testen:
composer require zunderweb/oxid-jxattredit:dev-multiselect

**Comment by flash7x** [comment]
Hallo leofonic, super danke!
In zwei Wochen kann ich es testen und gebe Rückmeldung.
Grüße

**Comment by flash7x** [comment]
Es funktioniert. Klasse, danke!

**Comment by flash7x** [comment]
Es funktioniert. Klasse, danke!
